// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddUser struct {
	Name *string `json:"name"`
	Age  *int    `json:"age"`
}

type User struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
	ID   string `json:"id"`
}

type UserSearchParam struct {
	Name *string `json:"name"`
	Age  *int    `json:"age"`
}
